name: e_shop
description: Flutter eCommerce App

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.2+1
  firebase_auth: ^0.15.4
  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+1
  firebase_storage: ^3.1.1
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^0.5.0+1
  image: ^2.0.7
  intl:
  badges: ^1.2.0
  custom_navigator: ^0.3.0
  persistent_bottom_nav_bar: ^4.0.2
  firebase_database: any
  http: ^0.12.2
  qr_flutter: ^4.0.0
  dio: ^3.0.10
  image_gallery_saver: ^1.6.6
  permission_handler: ^5.0.1+1
  qr_code_scanner: ^0.4.0  #qrcode scanner
  arcore_flutter_plugin:
  flutter_masked_text: ^0.8.0
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: true
  ios: true
  image_path: "images/main.png"
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Italianno-Regular
      fonts:
        - asset: assets/fonts/Italianno-Regular.ttf

  assets:
    - images/




